<testng-results>
    <reporter-output>
    </reporter-output>
    <suite name="Ant suite" duration-ms="29" started-at="2011-03-09T21:13:15Z" finished-at="2011-03-09T21:13:15Z">
        <groups>
        </groups>
        <test name="Ant test" duration-ms="29" started-at="2011-03-09T21:13:15Z" finished-at="2011-03-09T21:13:15Z">
            <class name="org.jenkins.TestDataProvider">
                <test-method status="FAIL" signature="test(int)" name="test" duration-ms="9" started-at="2011-03-09T21:13:15Z" finished-at="2011-03-09T21:13:15Z">
                    <params>
                        <param index="0">
                            <value>
                                <![CDATA[1]]>
                            </value>
                        </param>
                    </params>
                    <exception class="java.lang.AssertionError">
                        <full-stacktrace>
                            <![CDATA[java.lang.AssertionError
	at org.jenkins.TestDataProvider.test(TestDataProvider.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1007)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:932)
	at org.testng.TestNG.run(TestNG.java:868)
	at org.testng.TestNG.privateMain(TestNG.java:1150)
	at org.testng.TestNG.main(TestNG.java:1114)
]]>
                        </full-stacktrace>
                    </exception>
                </test-method>
                <test-method status="FAIL" signature="test(int)" name="test" duration-ms="1" started-at="2011-03-09T21:13:15Z" finished-at="2011-03-09T21:13:15Z">
                    <params>
                        <param index="0">
                            <value>
                                <![CDATA[3]]>
                            </value>
                        </param>
                    </params>
                    <exception class="java.lang.AssertionError">
                        <full-stacktrace>
                            <![CDATA[java.lang.AssertionError
	at org.jenkins.TestDataProvider.test(TestDataProvider.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1007)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:932)
	at org.testng.TestNG.run(TestNG.java:868)
	at org.testng.TestNG.privateMain(TestNG.java:1150)
	at org.testng.TestNG.main(TestNG.java:1114)
]]>
                        </full-stacktrace>
                    </exception>
                </test-method>
                <test-method status="PASS" signature="test(int)" name="test" duration-ms="0" started-at="2011-03-09T21:13:15Z" finished-at="2011-03-09T21:13:15Z">
                    <params>
                        <param index="0">
                            <value>
                                <![CDATA[2]]>
                            </value>
                        </param>
                    </params>
                </test-method>
                <test-method status="FAIL" signature="test(int)" name="test" duration-ms="1" started-at="2011-03-09T21:13:15Z" finished-at="2011-03-09T21:13:15Z">
                    <params>
                        <param index="0">
                            <value>
                                <![CDATA[5]]>
                            </value>
                        </param>
                    </params>
                    <exception class="java.lang.AssertionError">
                        <full-stacktrace>
                            <![CDATA[java.lang.AssertionError
	at org.jenkins.TestDataProvider.test(TestDataProvider.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1007)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:932)
	at org.testng.TestNG.run(TestNG.java:868)
	at org.testng.TestNG.privateMain(TestNG.java:1150)
	at org.testng.TestNG.main(TestNG.java:1114)
]]>
                        </full-stacktrace>
                    </exception>
                </test-method>
                <test-method status="PASS" signature="test(int)" name="test" duration-ms="0" started-at="2011-03-09T21:13:15Z" finished-at="2011-03-09T21:13:15Z">
                    <params>
                        <param index="0">
                            <value>
                                <![CDATA[4]]>
                            </value>
                        </param>
                    </params>
                </test-method>
                <test-method status="PASS" signature="test(int)" name="test" duration-ms="1" started-at="2011-03-09T21:13:15Z" finished-at="2011-03-09T21:13:15Z">
                    <params>
                        <param index="0">
                            <value>
                                <![CDATA[8]]>
                            </value>
                        </param>
                    </params>
                </test-method>
                <test-method status="FAIL" signature="test(int)" name="test" duration-ms="0" started-at="2011-03-09T21:13:15Z" finished-at="2011-03-09T21:13:15Z">
                    <params>
                        <param index="0">
                            <value>
                                <![CDATA[7]]>
                            </value>
                        </param>
                    </params>
                    <exception class="java.lang.AssertionError">
                        <full-stacktrace>
                            <![CDATA[java.lang.AssertionError
	at org.jenkins.TestDataProvider.test(TestDataProvider.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1007)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:932)
	at org.testng.TestNG.run(TestNG.java:868)
	at org.testng.TestNG.privateMain(TestNG.java:1150)
	at org.testng.TestNG.main(TestNG.java:1114)
]]>
                        </full-stacktrace>
                    </exception>
                </test-method>
                <test-method status="PASS" signature="test(int)" name="test" duration-ms="0" started-at="2011-03-09T21:13:15Z" finished-at="2011-03-09T21:13:15Z">
                    <params>
                        <param index="0">
                            <value>
                                <![CDATA[6]]>
                            </value>
                        </param>
                    </params>
                </test-method>
            </class>
        </test>
    </suite>
</testng-results>